metadata:
  simulation_name: "demo_aberrations"
  image_width: 512
  image_height: 512

optical_parameters:
  wavelength: "532nm"

noise_profiles:
  default_gaussian:
    sigma_percent: 0.4
    clip: false  # Permite valores fuera de rango

classes:
  simple_defocus:
    coefficients:
      - [2, 0, -2.0, 2.0]  # Defocus fuerte
    samples: 30
    noise:
      gaussian: true
      dust: 
        num_particles: [3, 5]

  coma_spherical:
    coefficients:
      - [3, 1, -0.7, 0.7]    # Coma horizontal
      - [4, 0, -0.4, 0.4]     # Esférica
    samples: 30
    noise:
      vibration:
        max_kernel_size: 25
      gaussian: true
      poisson: true
      dust: true
      