metadata:
  author: "isaul"
  simulation_name: "mixed_aberrations_demo"
  description: "Dataset de combinaciones controladas de aberraciones ópticas"
  date: "2025-04-15"
  image_height: 256
  image_width: 256

optical_parameters:
  wavelength: 632.8nm

noise_profiles:
  default_gaussian:
    sigma_percent: 0.3
    clip: true

classes:
  defocus_astigmatism:
    coefficients:
      - [2, 0, -1.0, 1.0]   # Defocus
      - [2, -2, -0.8, 0.8]   # Astigmatismo 0°
    samples: 50
    noise:
      gaussian: true

  coma_spherical:
    coefficients:
      - [3, 1, -0.7, 0.7]    # Coma horizontal
      - [4, 0, -0.4, 0.4]     # Esférica
    samples: 50
    noise:
      gaussian: true

  astigmatism_trefoil:
    coefficients:
      - [2, 2, -0.6, 0.6]    # Astigmatismo 45°
      - [3, 3, -0.5, 0.5]     # Trefoil 30°
    samples: 50
    noise:
      gaussian: true

  defocus_coma:
    coefficients:
      - [2, 0, -1.2, 1.2]    # Defocus
      - [3, -1, -0.6, 0.6]    # Coma vertical
    samples: 50
    noise:
      gaussian: true

  spherical_tilt:
    coefficients:
      - [4, 0, -0.5, 0.5]     # Esférica
      - [1, 1, -1.5, 1.5]      # Tilt horizontal
    samples: 50
    noise:
      gaussian: true