seed: 42                       # Semilla para reproducibilidad

normalize:
  type: "8bit"                 # "8bit" o "float"

augmentation:
  copies: 2                    # Número de aumentos por imagen
  rotation: True               # Aplicar rotaciones aleatorias
  noise: True                  # Añadir ruido gaussiano

split:
  test: 0.15                   # 15% para test
  val: 0.15                    # 15% para validación
  # El 70% restante es para entrenamiento