metadata:
  author: "Isaúl Tirado López"
  description: "Pure optical aberration dataset with realistic noise profiles"
  license: "CC-BY-NC-SA-4.0"
  date: "2025-04-13"

optical_parameters:
  wavelength: 632.8nm
  na: 0.25
  pixel_size: 5.86µm
  wavefront_units: µm

noise_profiles:
  default_gaussian:
    sigma_percent: 0.5
    clip: true
  default_poisson:
    scale: 1000
  default_dust:
    num_particles: [3, 7]
    max_radius: 15
    intensity: 0.0
  default_vibration:
    amplitude_px: [0.8, 1.5]
    num_frames: 5

classes:
  piston:
    coefficients:
      - [0, 0, -0.1, 0.1]
    noise:
      gaussian: true  # Usa valores de default_gaussian
      poisson: false
      dust: false
      vibration: false
    samples: 1000

  ytilt:
    coefficients:
      - [1, -1, -2.0, 2.0]
    noise:
      gaussian: true
      vibration: true  # Típico en sistemas mecánicos
    samples: 1000

  xtilt:
    coefficients:
      - [1, 1, -2.0, 2.0]
    noise:
      gaussian: true
      vibration: true
    samples: 1000

  defocus:
    coefficients:
      - [2, 0, -1.5, 1.5]
    noise:
      gaussian: true
      poisson: true  # Fundamental en desenfoque
      dust: true     # Partículas en lentes
    samples: 1000

  primary_astigmatism_0:
    coefficients:
      - [2, -2, -1.2, 1.2]
    noise:
      gaussian: true
    samples: 1000

  primary_astigmatism_45:
    coefficients:
      - [2, 2, -1.2, 1.2]
    noise:
      gaussian: true
    samples: 1000

  ycoma:
    coefficients:
      - [3, -1, -0.8, 0.8]
    noise:
      gaussian: true
      dust: true  # Mayor probabilidad en bordes ópticos
    samples: 1000

  xcoma:
    coefficients:
      - [3, 1, -0.8, 0.8]
    noise:
      gaussian: true
      dust: true
    samples: 1000

  trefoil_0:
    coefficients:
      - [3, -3, -0.6, 0.6]
    noise:
      gaussian: true
    samples: 1000

  trefoil_30:
    coefficients:
      - [3, 3, -0.6, 0.6]
    noise:
      gaussian: true
    samples: 1000

  primary_spherical:
    coefficients:
      - [4, 0, -0.5, 0.5]
    noise:
      gaussian: true
      poisson: true  # Relevante en alta precisión
    samples: 1000

  secondary_astigmatism_0:
    coefficients:
      - [4, -2, -0.4, 0.4]
    noise:
      gaussian: true
    samples: 1000

  secondary_astigmatism_45:
    coefficients:
      - [4, 2, -0.4, 0.4]
    noise:
      gaussian: true
    samples: 1000

  tetrafoil_0:
    coefficients:
      - [4, -4, -0.3, 0.3]
    noise:
      gaussian: true
    samples: 1000

  tetrafoil_22:
    coefficients:
      - [4, 4, -0.3, 0.3]
    noise:
      gaussian: true
    samples: 1000